#! /bin/sh

option=$(printf "Lock\nSuspend\nReboot\nPower Off" | rofi -dmenu -i)

case "$option" in
	"Lock") hyprlock ;;
	# "Suspend") systemctl suspend && hyprlock ;;
	"Suspend") systemctl suspend ;;
	"Reboot") reboot ;;
	"Power Off") shutdown -h now ;;
	*) exit 1 ;;

esac
